# Generated by Django 5.1.3 on 2025-01-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
